version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mediloop-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mediloop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mediloop-backend
    ports:
      - "8000:8000"
<<<<<<< HEAD
=======
    volumes:
      - .:/app
      - /app/frontend
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:5174
      - MONGO_DB_NAME=mediloop
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - JWT_SECRET=${JWT_SECRET:-123456}
>>>>>>> 3da149a (onboarding, dashboard nd scrie ai bug fixed)
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:5174
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mediloop-frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
